# Generated by Django 5.2.4 on 2025-08-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plcyNo', models.CharField(blank=True, max_length=30, null=True)),
                ('plcyNm', models.CharField(blank=True, max_length=100, null=True)),
                ('plcyKywdNm', models.CharField(blank=True, max_length=100, null=True)),
                ('plcyExplnCn', models.TextField(blank=True, null=True)),
                ('lclsfNm', models.CharField(blank=True, max_length=100, null=True)),
                ('mclsfNm', models.CharField(blank=True, max_length=100, null=True)),
                ('plcySprtCn', models.TextField(blank=True, null=True)),
                ('bizPrdBgngYmd', models.CharField(blank=True, max_length=20, null=True)),
                ('bizPrdEndYmd', models.CharField(blank=True, max_length=20, null=True)),
                ('bizPrdEtcCn', models.TextField(blank=True, null=True)),
                ('plcyAplyMthdCn', models.TextField(blank=True, null=True)),
                ('srngMthdCn', models.TextField(blank=True, null=True)),
                ('aplyUrlAddr', models.TextField(blank=True, null=True)),
                ('sbmsnDcmntCn', models.TextField(blank=True, null=True)),
                ('etcMttrCn', models.TextField(blank=True, null=True)),
                ('refUrlAddr1', models.TextField(blank=True, null=True)),
                ('refUrlAddr2', models.TextField(blank=True, null=True)),
                ('sprtSclCnt', models.CharField(blank=True, max_length=20, null=True)),
                ('sprtTrgtMinAge', models.CharField(blank=True, max_length=10, null=True)),
                ('sprtTrgtMaxAge', models.CharField(blank=True, max_length=10, null=True)),
                ('sprtTrgtAgeLmtYn', models.CharField(blank=True, max_length=10, null=True)),
                ('mrgSttsCd', models.CharField(blank=True, choices=[('0055001', '미혼'), ('005502', '기혼'), ('0055003', '무관')], max_length=10, null=True)),
                ('earnCndSeCd', models.CharField(blank=True, choices=[('0043001', '소득 무관'), ('0043002', '소득 하위 기준'), ('0043003', '일정 소득 기준'), ('0043004', '건강보험료 기준'), ('0043005', '중위소득 기준')], max_length=10, null=True)),
                ('earnMinAmt', models.CharField(blank=True, max_length=20, null=True)),
                ('earnMaxAmt', models.CharField(blank=True, max_length=20, null=True)),
                ('earnEtcCn', models.TextField(blank=True, null=True)),
                ('addAplyQlfcCndCn', models.TextField(blank=True, null=True)),
                ('ptcpPrpTrgtCn', models.TextField(blank=True, null=True)),
                ('nqCnt', models.CharField(blank=True, max_length=20, null=True)),
                ('rgtrInstCdNm', models.CharField(blank=True, max_length=30, null=True)),
                ('rgtrHghrkInstCdNm', models.CharField(blank=True, max_length=30, null=True)),
                ('zipCd', models.TextField(blank=True, null=True)),
                ('plcyMajorCd', models.CharField(blank=True, choices=[('0011001', '일자리'), ('0011002', '주거'), ('0011003', '복지'), ('0011009', '기타/참여')], max_length=10, null=True)),
                ('jobCd', models.CharField(blank=True, choices=[('0013001', '취업자'), ('0013010', '무관')], max_length=10, null=True)),
                ('schoolCd', models.CharField(blank=True, choices=[('0049005', '대학생'), ('0049010', '무관')], max_length=10, null=True)),
                ('aplyYmd', models.TextField(blank=True, null=True)),
                ('frstRegDt', models.TextField(blank=True, null=True)),
                ('lastMdfcnDt', models.TextField(blank=True, null=True)),
                ('sBizCd', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
