# Generated by Django 5.2.4 on 2025-08-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plcyNo", models.CharField(max_length=100, unique=True)),
                ("plcyNm", models.CharField(max_length=200)),
                ("plcyKywdNm", models.CharField(blank=True, max_length=200, null=True)),
                ("plcySprtCn", models.TextField(blank=True, null=True)),
                ("aplyPrdSeCd", models.CharField(blank=True, max_length=50, null=True)),
                ("bizPrdSeCd", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bizPrdBgngYmd",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("bizPrdEndYmd", models.CharField(blank=True, max_length=8, null=True)),
                ("bizPrdEtcCn", models.TextField(blank=True, null=True)),
                ("plcyAplyMthdCn", models.TextField(blank=True, null=True)),
                ("srngMthdCn", models.TextField(blank=True, null=True)),
                ("aplyUrlAddr", models.URLField(blank=True, max_length=500, null=True)),
                ("sbmsnDcmntCn", models.TextField(blank=True, null=True)),
                ("etcMttrCn", models.TextField(blank=True, null=True)),
                ("sprtTrgtMinAge", models.IntegerField(blank=True, null=True)),
                ("sprtTrgtMaxAge", models.IntegerField(blank=True, null=True)),
                (
                    "sprtTrgtAgeLmtYn",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("mrgSttsCd", models.CharField(blank=True, max_length=50, null=True)),
                ("earnCndSeCd", models.CharField(blank=True, max_length=50, null=True)),
                ("earnMinAmt", models.BigIntegerField(blank=True, null=True)),
                ("earnMaxAmt", models.BigIntegerField(blank=True, null=True)),
                ("earnEtcCn", models.TextField(blank=True, null=True)),
                ("addAplyQlfcCndCn", models.TextField(blank=True, null=True)),
                ("rgtrInstCd", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rgtrInstCdNm",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("zipCd", models.TextField(blank=True, null=True)),
                ("plcyMajorCd", models.CharField(blank=True, max_length=50, null=True)),
                ("jobCd", models.CharField(blank=True, max_length=50, null=True)),
                ("schoolCd", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
