# Generated by Django 5.2.4 on 2025-08-08 17:39

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plcyNo', models.CharField(blank=True, max_length=100, null=True)),
                ('plcyPvsnMthdCd', models.CharField(blank=True, choices=[('0042001', '인프라 구축'), ('0042002', '프로그램'), ('0042003', '직접대출'), ('0042004', '공공기관'), ('0042005', '계약(위탁운영)'), ('0042006', '보조금'), ('0042007', '대출보증'), ('0042008', '공적보험'), ('0042009', '조세지출'), ('0042010', '바우처'), ('0042011', '정보제공'), ('0042012', '경제적 규제'), ('0042013', '기타')], max_length=50, null=True)),
                ('plcyNm', models.CharField(blank=True, max_length=100, null=True)),
                ('plcyKywdNm', models.CharField(blank=True, max_length=100, null=True)),
                ('plcyExplnCn', models.TextField(blank=True, null=True)),
                ('lclsfNm', models.CharField(blank=True, max_length=50, null=True)),
                ('mclsfNm', models.CharField(blank=True, max_length=50, null=True)),
                ('plcySprtCn', models.TextField(blank=True, null=True)),
                ('bizPrdBgngYmd', models.CharField(blank=True, max_length=50, null=True)),
                ('bizPrdEndYmd', models.CharField(blank=True, max_length=50, null=True)),
                ('bizPrdEtcCn', models.TextField(blank=True, null=True)),
                ('plcyAplyMthdCn', models.TextField(blank=True, null=True)),
                ('srngMthdCn', models.TextField(blank=True, null=True)),
                ('aplyUrlAddr', models.TextField(blank=True, null=True)),
                ('sbmsnDcmntCn', models.TextField(blank=True, null=True)),
                ('etcMttrCn', models.TextField(blank=True, null=True)),
                ('refUrlAddr1', models.TextField(blank=True, null=True)),
                ('refUrlAddr2', models.TextField(blank=True, null=True)),
                ('sprtSclCnt', models.CharField(blank=True, max_length=50, null=True)),
                ('sprtTrgtMinAge', models.CharField(blank=True, max_length=50, null=True)),
                ('sprtTrgtMaxAge', models.CharField(blank=True, max_length=50, null=True)),
                ('sprtTrgtAgeLmtYn', models.CharField(blank=True, max_length=50, null=True)),
                ('mrgSttsCd', models.CharField(blank=True, choices=[('0055001', '기혼'), ('005502', '미혼'), ('0055003', '제한없음')], max_length=50, null=True)),
                ('earnCndSeCd', models.CharField(blank=True, choices=[('0043001', '무관'), ('0043002', '연소득'), ('0043003', '기타')], max_length=50, null=True)),
                ('earnMinAmt', models.CharField(blank=True, max_length=50, null=True)),
                ('earnMaxAmt', models.CharField(blank=True, max_length=50, null=True)),
                ('earnEtcCn', models.TextField(blank=True, null=True)),
                ('addAplyQlfcCndCn', models.TextField(blank=True, null=True)),
                ('ptcpPrpTrgtCn', models.TextField(blank=True, null=True)),
                ('inqCnt', models.CharField(blank=True, max_length=50, null=True)),
                ('rgtrInstCdNm', models.CharField(blank=True, max_length=50, null=True)),
                ('rgtrHghrkInstCdNm', models.CharField(blank=True, max_length=50, null=True)),
                ('zipCd', models.TextField(blank=True, null=True)),
                ('plcyMajorCd', models.CharField(blank=True, choices=[('0011001', '인문계열'), ('0011002', '사회계열'), ('0011003', '상경계열'), ('0011004', '이학계열'), ('0011005', '공학계열'), ('0011006', '예체능계열'), ('0011007', '농산업계열'), ('0011008', '기타'), ('0011009', '제한없음')], max_length=100, null=True)),
                ('jobCd', models.CharField(blank=True, choices=[('0013001', '재직자'), ('0013002', '자영업자'), ('0013003', '미취업자'), ('0013004', '프리랜서'), ('0013005', '일용근로자'), ('0013006', '(예비)창업자'), ('0013007', '단기근로자'), ('0013008', '영농종사자'), ('0013009', '기타'), ('0013010', '제한없음')], max_length=100, null=True)),
                ('schoolCd', models.CharField(blank=True, choices=[('0049001', '고졸 미만'), ('0049002', '고교 재학'), ('0049003', '고졸 예정'), ('0049004', '고교 졸업'), ('0049005', '대학 재학'), ('0049006', '대졸 예정'), ('0049007', '대학 졸업'), ('0049008', '석·박사'), ('0049009', '기타'), ('0049010', '제한없음')], max_length=100, null=True)),
                ('aplyYmd', models.TextField(blank=True, null=True)),
                ('frstRegDt', models.TextField(blank=True, null=True)),
                ('lastMdfcnDt', models.TextField(blank=True, null=True)),
                ('sbizCd', models.CharField(blank=True, choices=[('0014001', '중소기업'), ('0014002', '여성'), ('0014003', '기초생활수급자'), ('0014004', '한부모가정'), ('0014005', '장애인'), ('0014006', '농업인'), ('0014007', '군인'), ('0014008', '지역인재'), ('0014009', '기타'), ('0014010', '제한없음')], max_length=100, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
            ],
        ),
    ]
