# Generated by Django 5.2.4 on 2025-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_policy_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='plcyPvsnMthdCd',
            field=models.CharField(blank=True, choices=[('0042001', '인프라 구축'), ('0042002', '프로그램'), ('0042003', '직접대출'), ('0042004', '공공기관'), ('0042005', '계약(위탁운영)'), ('0042006', '보조금'), ('0042007', '대출보증'), ('0042008', '공적보험'), ('0042009', '조세지출'), ('0042010', '바우처'), ('0042011', '정보제공'), ('0042012', '경제적 규제'), ('0042013', '기타')], max_length=20, null=True),
        ),
    ]
