# Generated by Django 5.2.4 on 2025-08-16 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_remove_policy_zipcd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='aiSummary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Favorite_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_policy', to='policy.policy')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
