# Generated by Django 5.2.4 on 2025-08-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_policy_aisummary_favorite_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite_policy',
            old_name='policy_id',
            new_name='policy',
        ),
        migrations.RenameField(
            model_name='favorite_policy',
            old_name='user_id',
            new_name='user',
        ),
    ]
