# Generated by Django 5.2.4 on 2025-08-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_alter_policy_plcypvsnmthdcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='earnCndSeCd',
            field=models.CharField(blank=True, choices=[('0043001', '무관'), ('0043002', '연소득'), ('0043003', '기타')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='jobCd',
            field=models.CharField(blank=True, choices=[('0013001', '재직자'), ('0013002', '자영업자'), ('0013003', '미취업자'), ('0013004', '프리랜서'), ('0013005', '일용근로자'), ('0013006', '(예비)창업자'), ('0013007', '단기근로자'), ('0013008', '영농종사자'), ('0013009', '기타'), ('0013010', '제한없음')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='mrgSttsCd',
            field=models.CharField(blank=True, choices=[('0055001', '기혼'), ('005502', '미혼'), ('0055003', '제한없음')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='plcyMajorCd',
            field=models.CharField(blank=True, choices=[('0011001', '인문계열'), ('0011002', '사회계열'), ('0011003', '상경계열'), ('0011004', '이학계열'), ('0011005', '공학계열'), ('0011006', '예체능계열'), ('0011007', '농산업계열'), ('0011008', '기타'), ('0011009', '제한없음')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='sbizCd',
            field=models.CharField(blank=True, choices=[('0014001', '중소기업'), ('0014002', '여성'), ('0014003', '기초생활수급자'), ('0014004', '한부모가정'), ('0014005', '장애인'), ('0014006', '농업인'), ('0014007', '군인'), ('0014008', '지역인재'), ('0014009', '기타'), ('0014010', '제한없음')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='schoolCd',
            field=models.CharField(blank=True, choices=[('0049001', '고졸 미만'), ('0049002', '고교 재학'), ('0049003', '고졸 예정'), ('0049004', '고교 졸업'), ('0049005', '대학 재학'), ('0049006', '대졸 예정'), ('0049007', '대학 졸업'), ('0049008', '석·박사'), ('0049009', '기타'), ('0049010', '제한없음')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='sprtTrgtAgeLmtYn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='sprtTrgtMaxAge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='sprtTrgtMinAge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
