# Generated by Django 5.2.4 on 2025-08-20 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_rename_policy_id_favorite_policy_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='embedding',
        ),
        migrations.AddConstraint(
            model_name='favorite_policy',
            constraint=models.UniqueConstraint(fields=('user', 'policy'), name='uniq_user_policy'),
        ),
    ]
