# Generated by Django 5.2.5 on 2025-08-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_remove_policy_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='zipCd',
            field=models.CharField(blank=True, choices=[('0014001', '중소기업'), ('0014002', '여성'), ('0014003', '기초생활수급자'), ('0014004', '한부모가정'), ('0014005', '장애인'), ('0014006', '농업인'), ('0014007', '군인'), ('0014008', '지역인재'), ('0014009', '기타'), ('0014010', '제한없음')], max_length=100, null=True),
        ),
    ]
