# Generated by Django 5.2.4 on 2025-08-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_alter_policy_bizprdbgngymd_alter_policy_bizprdendymd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='lclsfNm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='mclsfNm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='plcyKywdNm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='plcyNm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='plcyNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
