# Generated by Django 5.2.5 on 2025-08-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_policy_zipcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='zipCd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
