# Generated by Django 5.2.4 on 2025-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_alter_policy_lclsfnm_alter_policy_mclsfnm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='plcyNm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
