# Generated by Django 5.2.4 on 2025-08-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Special",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=30)),
                (
                    "marry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0055001", "기혼"),
                            ("0055002", "미혼"),
                            ("0055003", "제한없음"),
                        ],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("max_income", models.IntegerField(blank=True, null=True)),
                (
                    "graduate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0049001", "고졸 미만"),
                            ("0049002", "고교 재학"),
                            ("0049003", "고졸예정"),
                            ("0049004", "고교 졸업"),
                            ("0049005", "대학 재학"),
                            ("0049006", "대졸 예정"),
                            ("0049007", "대학 졸업"),
                            ("0049008", "석·박사"),
                            ("0049009", "기타"),
                            ("0049010", "제한없음"),
                        ],
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "employment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0013001", "재직자"),
                            ("0013002", "자영업자"),
                            ("0013003", "미취업자"),
                            ("0013004", "프리랜서"),
                            ("0013005", "일용근로자"),
                            ("0013006", "(예비)창업자"),
                            ("0013007", "단기근로자"),
                            ("0013008", "영농종사자"),
                            ("0013009", "기타"),
                            ("0013010", "제한없음"),
                        ],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("goal", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile_Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "speical_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="profiles.major"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="majors",
            field=models.ManyToManyField(
                related_name="profiles",
                through="profiles.Profile_Major",
                to="profiles.major",
            ),
        ),
        migrations.CreateModel(
            name="Profile_Special",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "speical_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.special",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="special",
            field=models.ManyToManyField(
                related_name="profiles",
                through="profiles.Profile_Special",
                to="profiles.special",
            ),
        ),
    ]
