# Generated by Django 5.2.5 on 2025-08-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major_code',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='profiles.major'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special_code',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='profiles.special'),
        ),
    ]
