# Generated by Django 5.2.4 on 2025-08-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='label',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='special',
            name='label',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='majors',
            field=models.ManyToManyField(related_name='profile', to='profiles.major'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special',
            field=models.ManyToManyField(related_name='profile', to='profiles.special'),
        ),
        migrations.AlterField(
            model_name='special',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
