# Generated by Django 5.2.4 on 2025-08-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_major_label_special_label_alter_major_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='majors',
            new_name='major',
        ),
    ]
