# Generated by Django 5.2.5 on 2025-08-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_majors_profile_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='label',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='special',
            name='label',
        ),
        migrations.AddField(
            model_name='profile',
            name='majors',
            field=models.ManyToManyField(related_name='profiles', to='profiles.major'),
        ),
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(blank=True, choices=[('0011001', '인문계열'), ('0011002', '사회계열'), ('0011003', '상경계열'), ('0011004', '이학계열'), ('0011005', '공학계열'), ('0011006', '예체능계열'), ('0011007', '농산업계열'), ('0011008', '기타'), ('0011009', '제한없음')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special',
            field=models.ManyToManyField(related_name='profiles', to='profiles.special'),
        ),
        migrations.AlterField(
            model_name='special',
            name='code',
            field=models.CharField(blank=True, choices=[('0014001', '중소기업'), ('0014002', '여성'), ('0014003', '기초생활수급자'), ('0014004', '한부모가정'), ('0014005', '장애인'), ('0014006', '농업인'), ('0014007', '군인'), ('0014008', '지역인재'), ('0014009', '기타'), ('0014010', '제한없음')], max_length=30),
        ),
    ]
