# Generated by Django 5.2.5 on 2025-08-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_major_label_remove_profile_major_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='employment',
            new_name='employment_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='graduate',
            new_name='graduate_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='majors',
            new_name='majors_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='special',
            new_name='special_code',
        ),
    ]
