# Generated by Django 5.2.5 on 2025-08-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_employment_profile_employment_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='majors_code',
            new_name='major_code',
        ),
    ]
